apiVersion: v1
kind: Service
metadata:
    annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: '/health'
    labels:
        name: alertmanager
    name: alertmanager-svc
    namespace: monitoring
spec:
    selector:
        app: alertmanager
    type: NodePort
    ports:
        - name: alertmanager
          protocol: TCP
          port: 9093
          targetPort: 9093
          nodePort: 30083
