apiVersion: v1
kind: Service
metadata:
    name: prometheus-service
    namespace: monitoring
    labels:
        app: prometheus
    annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: '/health'
spec:
    selector:
        app: prometheus
    ports:
        - protocol: TCP
          port: 9090
          targetPort: 9090
          nodePort: 30081
    type: NodePort
