apiVersion: apps/v1
kind: Deployment
metadata:
    name: mysql-deployment
    namespace: db
spec:
    selector:
        matchLabels:
            app: mysql
    strategy:
        type: Recreate
    template:
        metadata:
            labels:
                app: mysql
        spec:
            containers:
                - name: mysql
                  image: mysql:8.0
                  env:
                      - name: MYSQL_ROOT_PASSWORD
                        value: 'password123'
                  ports:
                      - containerPort: 3306
                  volumeMounts:
                      - name: mysql-storage
                        mountPath: /var/lib/mysql
            volumes:
                - name: mysql-storage
                  persistentVolumeClaim:
                      claimName: mysql-pvc
