apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    name: ingress-role-binding
    namespace: ingress
subjects:
    - kind: ServiceAccount
      name: ingress
      namespace: ingress
roleRef:
    kind: Role
    name: ingress-role
    apiGroup: rbac.authorization.k8s.io
